name: map_box_app
description: "Technical test with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.6.3
  mapbox_maps_flutter: ^2.5.0
  permission_handler: ^11.3.1
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  http: ^1.2.2
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

